import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://xeradia.com"),

  title: {
    default: "Xeradia | Advanced Nanoceramic Coatings for Fusion and Fission",
    template: "%s | Xeradia",
  },

  description:
    "Xeradia develops advanced nanoceramic coatings for fusion and fission reactors, including tritium barriers, accident-tolerant fuel claddings, molten-metal corrosion protection and high-temperature coatings for Gen IV nuclear systems.",

  keywords: [
    "Xeradia",
    "Xeradia coatings",
    "nuclear coatings",
    "advanced nuclear coatings",
    "nanoceramic coatings",
    "ceramic coatings",
    "protective coatings",
    "functional coatings",
    "multifunctional coatings",
    "surface engineering",
    "advanced surface engineering",
    "thin film coatings",
    "thin film deposition",
    "high temperature coatings",
    "high-temperature ceramic coatings",
    "radiation resistant coatings",
    "irradiation resistant coatings",
    "corrosion resistant coatings",
    "molten metal corrosion protection",
    "molten lead corrosion protection",
    "liquid metal corrosion protection",
    "lead corrosion protection",
    "lead-bismuth corrosion protection",
    "Pb corrosion",
    "PbLi corrosion",
    "FLiBe corrosion",
    "molten salt corrosion",
    "molten salt reactor coatings",
    "nuclear materials",
    "advanced nuclear materials",
    "materials for nuclear energy",
    "nuclear reactor materials",
    "fusion materials",
    "fission materials",
    "fusion coatings",
    "fission coatings",
    "advanced fission coatings",
    "fusion reactor coatings",
    "fission reactor coatings",
    "Gen IV reactors",
    "Generation IV reactors",
    "IV Gen reactors",
    "IV generation reactors",
    "next generation nuclear reactors",
    "advanced reactors",
    "advanced nuclear reactors",
    "fast reactors",
    "fast neutron reactors",
    "lead cooled fast reactors",
    "lead-cooled fast reactors",
    "LFR",
    "LFR coatings",
    "LFR cladding",
    "LFR corrosion protection",
    "liquid metal fast reactors",
    "SMR",
    "small modular reactors",
    "SMR coatings",
    "microreactors",
    "accident tolerant fuel",
    "accident tolerant fuel cladding",
    "ATF",
    "ATF coatings",
    "ATF cladding",
    "fuel cladding",
    "fuel cladding coating",
    "cladding protection",
    "zirconium cladding",
    "zirconium alloy cladding",
    "steel cladding",
    "15-15Ti",
    "EUROFER",
    "EUROFER97",
    "AISI 316L",
    "nuclear fuel rods",
    "LOCA",
    "loss of coolant accident",
    "steam oxidation resistance",
    "oxidation resistant coatings",
    "tritium barrier",
    "tritium barriers",
    "tritium permeation barrier",
    "tritium permeation barriers",
    "tritium retention",
    "tritium economy",
    "hydrogen isotope barrier",
    "hydrogen isotope permeation",
    "deuterium permeation",
    "permeation reduction factor",
    "PRF",
    "fusion breeding blanket",
    "breeding blanket",
    "fusion blanket",
    "blanket coating",
    "tritium breeding blanket",
    "fusion fuel cycle",
    "fusion reactor materials",
    "DEMO reactor",
    "ARC reactor",
    "SPARC reactor",
    "tokamak materials",
    "stellarator materials",
    "plasma facing components",
    "first wall materials",
    "ALD",
    "Atomic Layer Deposition",
    "Atomic Layer Deposition nuclear",
    "ALD nuclear coatings",
    "ALD tritium barrier",
    "ALD ceramic coatings",
    "ALD alumina",
    "ALD Al2O3",
    "conformal coatings",
    "conformal ALD",
    "internal tube coatings",
    "heat exchanger tube coatings",
    "complex geometry coating",
    "PLD",
    "Pulsed Laser Deposition",
    "Pulsed Laser Deposition nuclear",
    "PLD nuclear coatings",
    "PLD ceramic coatings",
    "PLD alumina coatings",
    "laser deposition coatings",
    "dense multilayer coatings",
    "ceramic multilayers",
    "multilayer coating architecture",
    "amorphous alumina",
    "Al2O3 coatings",
    "alumina coatings",
    "yttria stabilized alumina",
    "YAlO",
    "LiYAlO",
    "yttria coatings",
    "Y2O3 coatings",
    "chromium coatings",
    "Cr coatings",
    "ceramic diffusion barrier",
    "diffusion barrier coatings",
    "environmental barrier coatings",
    "ductile amorphous ceramics",
    "DAC",
    "nuclear startup",
    "deep tech nuclear",
    "fusion startup",
    "advanced fission startup",
    "clean energy materials",
    "energy transition materials",
  ],

  authors: [{ name: "Xeradia" }],
  creator: "Xeradia",
  publisher: "Xeradia",
  applicationName: "Xeradia",
  category: "Advanced nuclear materials",

  alternates: {
    canonical: "https://xeradia.com",
  },

  openGraph: {
    title: "Xeradia | Advanced Nanoceramic Coatings",
    description:
      "Advanced ALD and PLD nanoceramic coating technologies for fusion reactors, Gen IV fission reactors, tritium barriers, accident-tolerant fuel claddings and molten-metal corrosion protection.",
    url: "https://xeradia.com",
    siteName: "Xeradia",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "/images/xeradia-plasma-hero.jpeg",
        width: 1200,
        height: 630,
        alt: "Xeradia advanced coating platform for nuclear materials",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Xeradia | Advanced Nanoceramic Coatings",
    description:
      "Advanced coating technologies for fusion, Gen IV fission reactors, tritium barriers, LFR cladding and high-temperature nuclear materials.",
    images: ["/images/xeradia-plasma-hero.jpeg"],
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
